steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/hello-world:${SHORT_SHA}', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/hello-world:${SHORT_SHA}']
    
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'hello-world'
      - '--image'
      - '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/hello-world:${SHORT_SHA}'
      - '--region'
      - '${LOCATION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/hello-world:${SHORT_SHA}'

substitutions:
  _REPOSITORY: cloud-run-source-deploy # Default repository name

options:
  logging: CLOUD_LOGGING_ONLY